# -*- coding: utf-8 -*-
"""titanic task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EE_z-h_Xn0HsLhpw0zarAfrcRpKcseR9
"""

import pandas as pd
df = pd.read_csv("/content/Titanic-Dataset.csv")
df.head()

df.info()

df.corr()

import seaborn as sns
sns.heatmap(df.corr())

df.hist();

df["Age"].hist();



df["Survived"].hist()

sns.countplot(df, x="Survived", hue="Sex")
plt.xlabel('Survived')
plt.ylabel('Count')